In [23]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv('./DataSet/trx-10k.csv')
df.dropna(inplace=True)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 9578 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     9578 non-null   object
 1   time       9578 non-null   object
 2   card_type  9578 non-null   object
 3   city       9578 non-null   object
 4   amount     9578 non-null   int64
 5   id         9578 non-null   int64
dtypes: int64(2), object(4)
memory usage: 523.8+ KB

             amount           id
count  9.578000e+03  9578.000000
mean   2.492398e+06    50.050324
std    1.442460e+06    28.917290
min    1.048100e+04     1.000000
25%    1.247962e+06    25.000000
50%    2.471254e+06    50.000000
75%    3.747052e+06    74.750000
max    4.997913e+06   100.000000

In [25]:
df.head()

    status                 time card_type     city   amount  id
0  success  2025-09-07 10:48:00      Visa   Tehran   470243  98
1  success  2025-09-20 13:10:00  MastCard   Tehran  4025070  52
2     fail  2025-09-29 03:27:00      Visa  Tehran   3573895  20
3  success  2025-09-15 13:13:00  Discover  Isfahan  4961173  40
4  success  2025-09-11 11:11:00      Visa   Tehran  2067746  59

In [26]:
# Lets Wash The Dirty Data :)
# Status Col

df['status'] = df['status'].str.lower().str.strip()
df['status'].unique()

array(['success', 'fail', 'failed', 'succeed'], dtype=object)

In [27]:
def status_cleaner(x:str):
    if x in ['success','succeed']:
        return 'success'
    
    elif x in ['fail','failed']:
        return 'fail'
    
    return np.nan

df['status'] = df['status'].apply(status_cleaner)

df['status'].dropna(inplace=True)
df['status'].unique()

array(['success', 'fail'], dtype=object)

In [28]:
# Time Col

df['time'] = pd.to_datetime(df['time'],errors='coerce',format='%Y-%m-%d %H:%M:%S')
df['time'].isnull().sum()

np.int64(0)

In [29]:
# Card Type Col

df['card_type'] = df['card_type'].str.lower().str.strip()
df['card_type'].unique()

array(['visa', 'mastcard', 'discover', 'master-card', 'amex',
       'mastercard', 'vsa', 'master card'], dtype=object)

In [30]:
def clean_CardType(x:str):
    if x in ['mastcard','master-card','mastercard','master card']:
        return "MasterCard"
    elif x in ['visa','vsa']:
        return "Visa"
    elif x == 'discover':
        return "Discover"
    elif x == 'amex':
        return 'Amex'
    
    return np.nan

df['card_type'] = df['card_type'].apply(clean_CardType)

df['card_type'].isnull().sum()

np.int64(0)

In [31]:
# City Col

df['city'] = df['city'].str.lower().str.strip()

df['city'].unique()

array(['tehran', 'isfahan', 'tabriz', 'shiraz', 'karaj', 'ahvaz', 'thr',
       'qom', 'mashhad', 'tehr@n', 'thran'], dtype=object)

In [32]:
def clean_city(x:str):
    if x in ['tehran','thr','tehr@n','thran']:
        return "Tehran"
    
    elif x in ['mashhad','qom','ahvaz','karaj','shiraz','tabriz','isfahan']:
        return x.capitalize()
    
    return np.nan

df['city'] = df['city'].apply(clean_city)
df['city'].isnull().sum()

np.int64(0)

In [33]:
df['city'].unique()

array(['Tehran', 'Isfahan', 'Tabriz', 'Shiraz', 'Karaj', 'Ahvaz', 'Qom',
       'Mashhad'], dtype=object)