In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
df = pd.read_csv('./DataSet/trx-10k.csv')
df.dropna(inplace=True)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 9578 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     9578 non-null   object
 1   time       9578 non-null   object
 2   card_type  9578 non-null   object
 3   city       9578 non-null   object
 4   amount     9578 non-null   float64
 5   id         9578 non-null   int64
dtypes: float64(1), int64(1), object(4)
memory usage: 523.8+ KB

             amount           id
count  9.578000e+03  9578.000000
mean   2.959419e+08    50.050324
std    1.693342e+09    28.917290
min   -9.999990e+05     1.000000
25%    1.005000e+02    25.000000
50%    3.436790e+05    50.000000
75%    9.144650e+05    74.750000
max    1.000000e+10   100.000000

In [21]:
df.head()

    status                 time card_type     city     amount  id
0  success  2025-09-07 10:48:00      Visa   Tehran  1427657.0  98
1  success  2025-09-20 13:10:00  MastCard   Tehran  1578078.0  52
2     fail  2025-09-29 03:27:00      Visa  Tehran    250000.0  20
3  success  2025-09-15 13:13:00  Discover  Isfahan        0.0  40
4  success  2025-09-11 11:11:00      Visa   Tehran  1782689.0  59

In [22]:
# Lets Wash The Dirty Data :)
# Status Col

df['status'] = df['status'].str.lower()
df['status'].unique()

array(['success', 'fail', 'failed', 'succeed'], dtype=object)

In [23]:
def status_cleaner(x:str):
    if x in ['success','succeed']:
        return 'success'
    
    elif x in ['fail','failed']:
        return 'fail'
    
    return np.nan

df['status'] = df['status'].apply(status_cleaner)

df['status'].dropna(inplace=True)
df['status'].unique()

array(['success', 'fail'], dtype=object)

In [24]:
# Time Col

df['time'] = pd.to_datetime(df['time'],errors='coerce',format='%Y-%m-%d %H:%M:%S')
df['time'].isnull().sum()

np.int64(0)